//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgelinkDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUs
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public Nullable<bool> OptIn { get; set; }
        public string FromLocation { get; set; }
        public Nullable<System.DateTime> CreatedDated { get; set; }
    }
}
